### PR TITLE
Allow users to set vm.swappiness.

### PR DESCRIPTION
**Pull request by elisiano**
Previously Cloudera recommended setting vm.swappiness to 0 but with
recent kernels the suggested value is 1.
http://www.cloudera.com/documentation/enterprise/5-5-x/topics/cdh_admin_performance.html

This change allows users to set vm.swappiness to their liking,
maintaining backward compatibility (defaults to 0).

### CODE REVIEW

**Comment by DonMaja** [comment]
please merge, make sense

**Comment by Naigy** [comment]
Please merge this as this is recommended by cloudera docs.

**Comment by razorsedge** [comment]
@elisiano Thank you for your submission.  As per the DEVELOP.md file, could you please resubmit from the `develop` branch?

**Comment by elisiano** [comment]
Changed the branch. I see the tests are failing but it doesn't look like the errors are related to the change. Is there something I should do to address that?

**Comment by razorsedge** [comment]
Those are the old tests.  Did you rebase against the latest `develop` branch changes?

**Comment by elisiano** [comment]
Oh no, I just changed the branch of the PR. I'll look into that.

**Comment by razorsedge** [comment]
This has been merged in commit 33cc31bc2806716fb5c507d51c61977ac400f078.

**Comment by elisiano** [comment]
I'm closing this given it's been merged somewhere else already.

**Pull request closed without merging**
